openapi: 3.0.1
info:
  title: Mock Payroll API
  description: A simple API to manage employees and calculate payroll.
  version: 1.0.0
servers:
  - url: http://localhost:4000
paths:
  /employees:
    get:
      summary: Get all employees
      responses:
        '200':
          description: A list of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
    post:
      summary: Add a new employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewEmployee'
      responses:
        '201':
          description: Employee created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
  /employees/{id}/payroll:
    get:
      summary: Calculate payroll for an employee
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The employee ID
      responses:
        '200':
          description: Payroll details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payroll'
        '404':
          description: Employee not found
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
        hourlyRate:
          type: number
          format: float
          example: 20
        hoursWorked:
          type: number
          format: float
          example: 40
    NewEmployee:
      type: object
      properties:
        name:
          type: string
          example: Alice Johnson
        hourlyRate:
          type: number
          format: float
          example: 25
        hoursWorked:
          type: number
          format: float
          example: 30
    Payroll:
      type: object
      properties:
        employeeId:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
        totalPay:
          type: number
          format: float
          example: 800
